### ISSUE TITLE
Start reply at top of email

### ISSUE THREAD

**Issue by tlrmcknz** [RainLoop/rainloop-webmail#865] opened 2015-10-23 15:11 UTC
Perhaps I'm overlooking something, but I don't see any setting to automatically place the cursor at the top of the reply as opposed to the bottom like it is now.

**Comment by amdavidson** [comment] 2015-12-09 17:20
If your editor is "Plain" or "Plain (forced)", rainloop will place your signature at the top of the email (top posting) but will place the cursor at the bottom, the html editor gets this right.

I would like a setting to chose top / bottom posting, but that's not quite what you're asking for.

I'm guessing that this is a duplicate of #327.

**Comment by anoxi** [comment] 2016-05-13 12:51
I can confirm this issue on Rainloop 1.10.0.103 and it's really annoying.
More in detail, the issue always happens with "Plain (forced)" or with "Plain" and plain-text reply.

**Comment by verilucis** [comment] 2016-12-25 16:46
Yes, just installed and everything I love about Rainloop so far, but for me, this is a true bummer!  Perhaps someone will take a look and get this fixed?  

Thanks!  Merry Christmas!  

+1

**Comment by marvhh** [comment] 2017-04-05 13:27
I also would like to see a setting to chose top / bottom posting

**Comment by floreal797** [comment] 2017-05-22 08:20
I love rainloop but it's really a bad idea to reply at the bottom of the original message... Please add an option to enable replying at top by default!

**Comment by DougBeney** [comment] 2017-09-18 19:54
Hmm. This seems silly. Still no fix in 2017?

**Closed** 2017-09-20 17:26 UTC
