### ISSUE TITLE
Implement 2-factor auth on admin login

### ISSUE THREAD

**Issue by Orbixx** [RainLoop/rainloop-webmail#799] opened 2015-08-14 09:33 UTC
Makes 2FA on user accounts pretty redundant if somebody is able to gain access to an admin account without 2FA then turn off 2FA for users.

**Comment by Orbixx** [comment] 2015-08-19 10:47
As far as I can see, it's not easy to block access to the admin page either, due to how URL redirects are handled within Rainloop, so I'm not sure how to use .htaccess to block it for example.

**Comment by megadr01d** [comment] 2015-09-19 15:51
Duplicate of https://github.com/RainLoop/rainloop-webmail/issues/755.

**Comment by RainLoop** [comment] 2015-09-19 16:28
@Orbixx 

You may turn off admin panel in main configuration file.

`./data/.../application.ini`

```ini
[security]
allow_admin_panel = Off
```

// closed as a duplicate

**Closed by RainLoop** 2015-09-19 16:28 UTC
