### ISSUE TITLE
'to' input in compose form hide content and wrongly interpret it

### ISSUE THREAD

**Issue by nbbn** [RainLoop/rainloop-webmail#737] opened 2015-07-01 14:34 UTC
Hello, I pasted by mistake multi-line message to "to" input in compose form.
The problem is, that rainloop made it invisible and impossible to delete (by backspace and delete keys). Then you rite to empty input e-mail address and then it's deformed by rainloop.

To make it clear, to reproduce problem:
  1. compose new message.
  2. paste in 'to' field text, e.g. 
```` Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum````
  3. Write in 'to' field (that looks empty) correct e-mail address (e.g. example@example.com).
  4. safe as draft (but sending will send with to malformed address too).
  5. open your draft, you will see:
````
To: "Lorem ipsum dolor sit amet,consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,sunt in culpa qui officia deserunt mollit anim id est" <laborum,example@example.com>
````

My comments:
maybe limiting size of e-mail address' description is an good idea?
maybe adjustment of input's size is an good idea?

tested on Chromium and Iceweasel (Firefox) with the newest rainloop.

**Comment by RainLoop** [comment] 2015-07-01 21:45
Thanks, I have understood what the problem is. It will be fixed in the new version

**Comment by nbbn** [comment] 2015-07-21 20:25
Fixed, thanks.

**Closed** 2015-07-21 20:25 UTC
