### ISSUE TITLE
PGP Signing problems

### ISSUE THREAD

**Issue by plumpudding** [RainLoop/rainloop-webmail#1021] opened 2016-05-02 22:01 UTC
This is probably related to my setup, so I'll describe it as detailed as possible:

I use the latest Rainloop release as of this date.
I imported an encrypted PGP private key, which contains subkeys for 3 addresses. 
I changed my default identity by editing the config files (Should there be a GUI option to change the default identity??).
I tried to sign a message. The key shows up. I press sign. 

`OpenPGP error: Error: Error signing cleartext message!`

The console says something about the private key not being decrypted, but I wasn't asked for a password. 

This might relate to #672.

**Comment by esroyo** [comment] 2016-05-03 15:33
Looks like a duplicate of  #1007

**Comment by plumpudding** [comment] 2016-05-03 15:37
I will try master when I find the time

**Comment by RainLoop** [comment] 2016-05-17 18:04
Fixed in the last version.

**Closed by RainLoop** 2016-05-17 18:04 UTC
